### ISSUE TITLE
Mising text after line that looks like a comment

### ISSUE THREAD

**Issue by JeremyPouyet** [html-to-text/node-html-to-text#152]
I have the following HTML:

```<html><head><title>Vous Etes Perdu ?</title></head><body><h1>Perdu sur l'Internet ?</h1><h2>Pas de panique, on va vous aider</h2><strong><pre>    * <---- vous &ecirc;tes ici .</pre></strong></body></html>``` 
from the website http://perdu.com/

The problem is that the following html is transformed into
```
Perdu sur l'Internet ?
Pas de panique, on va vous aider
    *
```

Instead of:

```
Perdu sur l'Internet ?
Pas de panique, on va vous aider
    * <---- vous êtes ici . 
```

The point is that I got the good result if I remove the character `<` of the third line. I think node-html-to-text interpret this line as a comment.
I use the following code but I don't think It's the reason why there is an issue:

```js
const htmlToTextOpts = {
  uppercaseHeadings: false,
  wordwrap: false,
  noLinkBrackets: true,
  hideLinkHrefIfSameAsText: true
};
console.log(htmlToText.fromString(html, htmlToTextOpts));
```
with `html` the not modified previously pasted html

PS: In english the text means "Lost on the internet ? Don't worry we'll help you * <---- You're here ."

**Comment by KillyMXI** [comment]
This issue is happened because [htmlparser2](https://github.com/fb55/htmlparser2) was not particularly smart when deciding what is a tag and what isn't,
It was considering `<---- vous &ecirc;tes ici .` as a tag (not a comment).

Good news is that it got somewhat smarter recently.
`html-to-text` version 7 depends on `htmlparser2` version that doesn't consider this as a tag anymore, thus resolving this particular issue.

Still, `htmlparser2` is not perfect at correcting human mistakes.
And using unescaped `<` in HTML is a mistake. `&lt;` should be used instead.
