### ISSUE TITLE
Sibling divs don't add new line.

### ISSUE THREAD

**Issue by joefradley** [html-to-text/node-html-to-text#174]
This html:
```
<div>
	<span style="font-family: Georgia, serif; font-size: 18px;">Dear John,</span>
</div>
<div>
	<span style="font-family: Georgia,serif;">I hope this letter finds you well....</span>
</div>
```

ideally should produce the following output:
```
Dear John,
I hope this letter finds you well...
```

but instead produces this output:
```
Dear John,I hope this letter finds you well...
```

**Comment by gillesKuhorn** [comment]
I've had the same issue. I've used :
`string.replace(new RegExp('<div>','g'), '<br><div>');`
The same happened for `<td>hello</td><td>star</td>` i would like the output :
`hello
star`
Is there a better way to handle all those cases ?

**Comment by sbj42** [comment]
A possible workaround is to replace all `div` tags with `p` tags before running `html-to-text`:
```js
html = html.replace(/<div>/g, '<p>').replace(/<\/div>/, '</p>');
```

But I think it would be better if html-to-text handled this more directly.

**Comment by josdejong** [comment]
Thanks @sbj42 your workaround works nicely, I solved like this:

```js
const text = htmlToText
  .fromString(
    html.replace(/<\/div>/g, '</div></br>'), // add </br> after each </div>
    options
  )
  .replace(/\n{3,}/g, '\n\n') // replace repeated '\n\n\n\n...' with just two '\n\n'  
```

**Comment by manojchowdary27** [comment]
@josdejong @sbj42 . Your workaround solution is not solving the actual requirement :)

The solution is actually inserting two line breaks instead of one. Because there is already one line break after `</div>`. And now we are transforming `div` into `p`. It will insert another line break.
So the final output will look like this.

![Screenshot 2020-04-06 at 2 34 23 PM](https://user-images.githubusercontent.com/24810514/78541728-b97e5f00-7813-11ea-966e-dcb7ffeecaed.png)

But the requirement is to insert only one line break.

**Comment by KillyMXI** [comment]
Version 6 is now aware of block-level tags and separates them with a single line break (except some tags that use more line breaks). 

Exact number of leading and trailing line breaks is configurable for individual tag names.
