### ISSUE TITLE
lodash version should be upgraded up to 4.17.21

### ISSUE THREAD

**Issue by skorolev-tjc** [html-to-text/node-html-to-text#225]
**Problem to solve**
We use  node-html-to-text 6.0.3 in our product and recently WhiteSource reported high vulnerability issue with lodah prior to 4.17.21.

**What is missing**
Currently your packeg-lock.json shows that lodash 4.17.20 is used in your package. Should be 4.17.21.

**How the missing feature should be implemented**
Upgrade dependencies

**Bigger picture**
the package would be less vulnerable.

Thank you

**Comment by KillyMXI** [comment]
Wow. I didn't know there is a version 6.0.3 of node-html-to-text... What exactly you're using?

If you're using 6.0.0 then you probably have even older version of lodash.
That's right that the current version (7.0.0) has lodash version 4.17.20 in the package-lock file.

If there is a serious vulnerability, I expect GitHub's dependabot to raise a warning soon and then I'll fix it in no time.

In the meanwhile I'd like to see a link to CVE.

Because lodash is only linked via dev dependencies - I don't see a reason to panic. Still, it's a shame it will haunt us even if we don't depend on it directly.

**Comment by KillyMXI** [comment]
Ok, here there are reported vulnerabilities on snyk:

https://snyk.io/vuln/npm:lodash@4.17.20

And on CVE:

* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23337
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28500

Doesn't make me think it's applicable to node-html-to-text. But I'll update package-lock anyway, soon.

**Comment by skorolev-tjc** [comment]
Thank you.
Yes, we have [CVE-2021-23337](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-23337).

**Comment by KillyMXI** [comment]
Updated in 7.1.1
