### ISSUE TITLE
Add span element in selectors list

### ISSUE THREAD

**Issue by prakashmallow** [html-to-text/node-html-to-text#234]
You missed html span element in selectors list. Most of emojis are handled in span element. In that scenario your plugin missed span on selectors list.

**Comment by KillyMXI** [comment]
By default, span elements are captured by universal selector and handled as inline elements. This is the only meaningful behavior for unstyled text.

Their usage for icons is implementation-specific. Different icon systems can opt for `<i>` elements or anything else instead.
These icon systems has nothing to do with Unicode emojis.

Following html fragment `<span class="material-icons-outlined">settings</span>` contains the word "settings" that will be preserved in the output text.

Following html fragment `<span class="material-icons-outlined"></span>` contains no text. It is shown in browser purely with help of CSS/JS.

You can override the default behavior and provide a custom formatter for all span elements or just for specific selectors.
You will have to make a custom formatter to extract the icon name from class name of the icon element and maybe provide a mapping from possible icon names to Unicode emojis.

Since it is implementation-specific (there are many icon systems) - it is out of scope of this package itself. The package provides enough tools for you to add the support yourself though.

**Comment by prakashmallow** [comment]
> By default, span elements are captured by universal selector and handled as inline elements. This is the only meaningful behavior for unstyled text.
> 
> Their usage for icons is implementation-specific. Different icon systems can opt for `<i>` elements or anything else instead.
> These icon systems has nothing to do with Unicode emojis.
> 
> Following html fragment `<span class="material-icons-outlined">settings</span>` contains the word "settings" that will be preserved in the output text.
> 
> Following html fragment `<span class="material-icons-outlined"></span>` contains no text. It is shown in browser purely with help of CSS/JS.
> 
> You can override the default behavior and provide a custom formatter for all span elements or just for specific selectors.
> You will have to make a custom formatter to extract the icon name from class name of the icon element and maybe provide a mapping from possible icon names to Unicode emojis.
> 
> Since it is implementation-specific (there are many icon systems) - it is out of scope of this package itself. The package provides enough tools for you to add the support yourself though.

Please give exmaple of custom formatter on html-to-text

**Comment by KillyMXI** [comment]
<https://github.com/html-to-text/node-html-to-text#override-formatting>
