### ISSUE TITLE
Option to add space between link url and brackets

### ISSUE THREAD

**Issue by JuanIrache** [html-to-text/node-html-to-text#236]
**Problem to solve**
Some browsers or email clients are interpreting the closing ] bracket of a link as part of the url

**What works**
You can remove brackets, but I'd rather have them

**What is missing**
There's no option to leave brackets on but add a space between them and the link

**How the missing feature should be implemented**
An option like noLinkBrackets

**Comment by KillyMXI** [comment]
Hmm. There is a valid point here, when dealing with real-world systems.
But at the same time this request looks terribly specific (for the lack of a better word).

[Existing formatter](https://github.com/html-to-text/node-html-to-text/blob/79f673106a63f467d1f43772840ecdb0527f91fe/lib/formatter.js#L158-L195) looks quite bad already from the amount of customizations.

As a workaround, you can take it as a base for your custom formatter right now (see Readme [section](https://github.com/html-to-text/node-html-to-text#override-formatting)).

I'll think about a nicer way to customize the link format compared to another boolean option.
There are one or two legacy options elsewhere in built-in formatters that are rather arbitrary and I'm trying to not introduce more. It must be pretty universal, otherwise a custom formatter is the way to go.

**Comment by JuanIrache** [comment]
Thank you. That makes sense.

I guess another solution would be adding spaces between urls and brackets by default. I do get clicks on links ending in ] quite often

**Comment by KillyMXI** [comment]
With version 8.1.0 you can now specify bracket strings for links and images:

```js
{
  selectors: [
    { selector: 'a', options: { linkBrackets: ['[ ',' ]'] } },
    { selector: 'img', options: { linkBrackets: ['[ ',' ]'] } }
  ]
}
```

**Comment by webstech** [comment]
> With version 8.1.0 you can now specify bracket strings for links and images

@KillyMXI  Curious as to why this is an array and not  `{ "[", "]" }`, which could be uniquely typed.

**Comment by KillyMXI** [comment]
@webstech I haven't spent much time considering the options, honestly.
Below are partly old and partly current considerations:

- using literal `[` and `]` keys inside `linkBrackets` didn't cross my mind. It seems clever but I'm not completely sure it's the best idea;
- any other names would take more space than it deserves. And the naming is hard, meaning there are even more fuel for the paralysis of choice;
- another level of nesting is not good. I'm not quite happy with the current situation already;
- I thought about separate `leftBracket` and `rightBracket` keys for left and right bracket directly in the `options` object. I think it is the most sensible alternative, but I decided I don't like to separate an inseparable entity, in addition for it being mouthful;
- using `[` and `]` keys directly inside `options` object seems to me like a really bad idea, something doubly unexpected, clever in a bad way.
- array serves as a poor man's tuple in a situation where the number and the ordering of items rather obvious, and it allows to not invent extra names. So it just felt least bad for me.

Thinking about it now, after implementing the new CLI (not public yet), every extra non-word characters you'd have to type in command line can become a source of issues. It can't be helped with more complex selectors, but at least for "static" keys I can avoid complicating the client's life.
