### ISSUE TITLE
It seems the format option `noLinkBrackets` already removed on v8.1.0

### ISSUE THREAD

**Issue by percy507** [html-to-text/node-html-to-text#249]
As the `README` says, the option `noLinkBrackets` will be removed on v9.

But after testing, it seems have been removed on v8.1.0. Well, it's ok on v8.0.0.

**Comment by KillyMXI** [comment]
Looks like a bug.
I put the [code](https://github.com/html-to-text/node-html-to-text/blob/8.1.0/lib/html-to-text.js#L313-L317) to handle `noLinkBrackets` but it doesn't seem to work as expected.

I should've tested it more carefully. Instead, I updated all tests to the new code at once and missed this.

Wonder whether I should really fix it.

**Comment by percy507** [comment]
Thanks for this project.  It really helpful. 😜

I think it's ok to ignore it. You can focus on the next big version. 

This issue can make a hint for someone who face the same question.

**Comment by KillyMXI** [comment]
I decided to take another look at this while I'm at it fixing the `minimist` issue.

Version 9 is getting delayed further more anyway, due to external reasons.

Turns out the issue is a bit more involved and can possibly manifest itself in different situations. So it's good to be fixed.

A merged/deduplicated copy of `options.selectors` was used as the source for the selectors decision tree but the original with duplicates was not replaced.
Any downstream code should not be concerned about duplication/partial selector definitions. In the version 8.2.0 `options.selectors` array itself is fully processed and downstream code can see it this way.

**Comment by webstech** [comment]
Not asking for a change but this patch broke the typescript type definitions test.  The test has no `format` specified:
```
    tags: {
        a: {
            options: {
                hideLinkHrefIfSameAsText: true,
                linkBrackets: ["[", "]"],
            },
        },
```
This results in `Error: Following selectors have no specified format: 'a'`

It previously worked with the default format getting merged but that does not happen now.  Also noting that in  `handleDeprecatedOptions` there are a number of checks for the format value that may not have been set yet.  Maybe needed a second call to `mergeDuplicatesPreferLast` after pushing all the tags to selectors.
