### ISSUE TITLE
Is is possible to include plain text as a child of <table>?

### ISSUE THREAD

**Issue by dprensha** [html-to-text/node-html-to-text#272]
**The goal**
I'm wanting to use this utility to format our email templates which use [Handlebars](https://handlebarsjs.com/) so that we can generate a plain text template of the email from the HTML template. However, there are times where we want to have a table row for each data item using an {{# each}} block such as below. This will add table rows for each item in the "Names" array.

```
<table cellpadding="0" cellspacing="0">
    <tr>
        <td width="60" class="materialTableHeader">Id</td>
        <td width="392" class="materialTableHeader">Title</td>
    </tr>
    \{{#each Names}}
        <tr>
            <td class="materialTableCell">\{{Id}}</td>
            <td class="materialTableCell">\{{Name}}</td>
        </tr>
    \{{/each}}
</table>
```

**The issue i'm experiencing is that because "plain text" is technically not allowed as a child  of `<table>`, is is removed from the output. Sure maybe it's not completely valid html but it would nice to include the handlebars markup somehow.**

**Best attempt**
I've tried wrapping the handlebars {{}} blocks in custom tags and using a custom selector & formatter, but I haven't gotten that to work. I've also tried wrapping the handlebars {{}} blocks in valid HTML, which works only sometimes based on our templates.

**The question**
Is there a way to include non-valid HTML such as this and include it within the final output?

**Prior research**
I looked all through the documentation and couldn't find anything on this. I did even check out htmlparser2 and it didn't seem to complain too much about this.

**Comment by KillyMXI** [comment]
```js
const options = {
  selectors: [
    { selector: 'table.a', format: 'block' },
    { selector: 'table.b', format: 'dataTable' },
    { selector: 'table.c' }, // 'block' by default
  ]
};
```
What `format` have you specified for tables in `html-to-text` options?

[The code](https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-text/src/text-formatters.js#L315-L381) of `dataTable` formatter only looks for proper table contents. But it might be not what you need, since you plan to evaluate the template after conversion, so no table formatting can be done properly at this point.

By default, format is set to `block`, and all contents are interpreted as inline tags (I might need to add default entries for rows at least to interpret them as blocks as well but I haven't done it yet.)
It produces output like this:
```
Id Title {{#each Names}} {{Id}} {{Name}} {{/each}}
```
(Not sure about the purpose of single backslashes in your example. Escaped backslash `\\` will also be preserved if needed.)

Depending on your desired output, you may adjust the options for `table`/`tr`/`td` tags using existing formatters or make a custom formatter for the whole table or its parts.

You may find interesting an example of tab-delimited table: https://github.com/html-to-text/node-html-to-text/issues/242#issuecomment-1000259286
