### ISSUE TITLE
Preview extracted correctly, but actual content is missing

### ISSUE THREAD

**Issue by Myzel394** [html-to-text/node-html-to-text#318]
**Minimal HTML example**

The email HTML is a redacted Facebook account suspension notice at https://privatebin.net/?ddf60efea3f6943e#Fo2eZqnZMvzBa7GWzVYwqjVeeQWNuTCuaHR2QXHNT6Pz

**Options**
Default / none

**Observed output**

It seems only the preview text is correctly extracted:

```
Your account has been suspended.    

 

   

[https://facebook.com/images/developer/app/dashboard/product-icons/whatsapp.png]
https://facebook.com/accountquality/1234 WhatsApp Business Platform
```

**Expected output**
Everything from line 195 to the bottom is missing (the actual content of the email)

**Version information**

- html-to-text: 9.0.5
- node: v20.14.0

----

**Comment by KillyMXI** [comment]
(Actual latest version is 9.0.5)

Curious HTML example.
It seems very liberal about closing tags, but that's not the issue.
Actual issue is that they put `body` tag in the middle of the document, while default options of `html-to-text` expect it to contain all meaningful content of the page.

Solution: use following options:

```
{
  'baseElements': { 'selectors': ['html'] }
}
```

**Comment by KillyMXI** [comment]
No follow-up, so I consider this solved.

I also see no need to reconsider the default. I can't find any mentions of such placement of `body` tag as a wide-spread HTML email formatting hack. (May reconsider if shown more evidence and purpose.)

Closing.
